Feature: Make a book catalog page with a new design JC-596
saritasa-nest/camp-js-2024-dat-ngo pull request #1
Opened 2024-07-04 08:46 UTC by datngo-saritasa

Make a book catalog page based on Figma design [JC-596](https://saritasa.atlassian.net/jira/software/c/projects/JC/boards/484?selectedIssue=JC-596)

2024-07-04 09:41 UTC, daoduong-saritasa requested changes

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +  --container-width: 1244px;
This can be place in `variables.css` in global, when we develop multiple features and pages, we should expect all of it have the same width for it's container, if some special case where it's container need other width then we will do it like this.

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +.main-section__books-wrapper {
It's weird to have main and section together, it's two separate tag, consider using one. I see this class use in html file and I think this should be main

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +.form__checkbox {
Checkbox should be the same naming with other element
```suggestion
.form-control__checkbox {
```

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +.footer_copyright {
```suggestion
.footer__copyright {
```

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Do we need this class at all?

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/global/variables.css
> +  --filter-size-xl: 360px;
`filter-size` doesn't have any meaning. I think change to `filter-width` would be better

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +    <header class="header font-logo">📚 Books app</header>
`header` should has it's own font if a logo has one, as this is a header block and it contain a image as a logo, so naming the font to `font-header` would be more correct
```suggestion
    <header class="header font-header">📚 Books app</header>
```

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +    <section class="main-section">
This should be `main` as I mention above
```suggestion
    <main class="main">
```

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +        <div class="font-subtitle books-wrapper__books-year">2022 year</div>
Please use other element to display text other than `div`, consider using heading tags if it's a title of a section, or `p` if it's a paragraph, or `span` if it's just text or a note.

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +        <div class="font-subtitle books-wrapper__books-year">2022 year</div>
As I review the design, the title in header can be `h1`, and then all the `Year title` can be `h2`

2024-07-04 09:41 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +        <div class="font-subtitle books-wrapper__books-year">2022 year</div>
And this is not a subtitle, this is actually title of a list of book that is filtered in year. Consider changing class name.

2024-07-04 09:46 UTC, khoanguyen-saritasa requested changes

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/global/components.css
> +/* a,
Please don't leave any code comments without any reason. If the code can be removed, do so to maintain a cleaner code style.

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/global/variables.css
> +  --font-size-xl: 20px;
Usually, for a typo system, especially `font-size`, we prefer using relative units rather than absolute units. Using `px` or any absolute units can lead to the issue, which will override a user's browser preferences, preventing the text from getting larger or smaller than the user prefers. So, it would be great if you could transform those `px` variables into `rem` (usually we use that unit for relative).

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/global/variables.css
> +
Same as above with line height

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +}
This style can be reused, so I think it would be better if you move it to a separate file. You can named it `utils.css` and store all your reusable styles.

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +            <div class="font-body-small truncate">Blue Period</div>
For a plain text, please use `p` tag to improve semantic HTML.

2024-07-04 09:46 UTC, khoanguyen-saritasa commented on apps/vanilla/src/pages/index.html
> +          <div class="font-subtitle">Filter</div>
Prefer `p` tag.

2024-07-04 09:55 UTC, khoanguyen-saritasa commented
And maybe you want to try grid layout instead of flex for the container. Please refer to this comment https://github.com/saritasa-nest/camp-js-2024-man-pham/pull/2#discussion_r1665225626 from Russian team for more detail.

2024-07-04 10:00 UTC, khoanguyen-saritasa commented
And one more thing. Let's add inline padding to the container so the page will have space between the content and the edge of the screen and the web will look better.
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/108647361/2a0b79dd-9cca-4853-90ac-a249c70009ee)

2024-07-04 10:02 UTC, daoduong-saritasa requested changes
- App break when using `iPad Air` Dimension device in Chrome ( No padding, filters and book image is lost when app width exceed screen width) 
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/108647643/a107ec45-4eeb-4bf7-b813-83e60ad9771d)

- Focus ring should outline the whole component, the same with sort field
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/108647643/91c03a94-dc7d-4318-8170-bb7b7123c864)

- `FILTER` title spacing not enough with below element according to figma and it's plural so missing `S`. Please use image above for example.

2024-07-04 10:14 UTC, datngo-saritasa commented on apps/vanilla/src/pages/index.css
> +  --container-width: 1244px;
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/174302261/9de21913-f6b7-4ed6-9753-2754549c2b47)
I got the idea of reusable variable this --container-width only use to make the code readable and --container-width itself changes in different media query so if I give its a global variable name then I have to make 3-4 new variables and use each one once time.

2024-07-04 11:13 UTC, datngo-saritasa commented on apps/vanilla/src/pages/index.html
> +    <header class="header font-logo">📚 Books app</header>
this one is also use for the footer so its shouldn't be font-header
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/174302261/6e6abc2b-88a3-4fdb-b104-135dd761dc53)

2024-07-04 11:37 UTC, datngo-saritasa commented on apps/vanilla/src/global/variables.css
> +  --font-size-xl: 20px;
I agree with you on the typo system, however the Figma design specify the font-size on pixel so I think it's inconvenient in this project to convert the px to rem. In real project we should have a default font size to convert

2024-07-04 11:37 UTC, datngo-saritasa commented on apps/vanilla/src/global/variables.css
> +
Same reason with above

2024-07-04 11:39 UTC, datngo-saritasa commented on apps/vanilla/src/pages/index.html
> +            <div class="font-body-small truncate">Blue Period</div>
Fixed

2024-07-04 11:39 UTC, datngo-saritasa commented on apps/vanilla/src/pages/index.html
> +          <div class="font-subtitle">Filter</div>
Fixed

2024-07-05 02:12 UTC, violetta-klintsova requested changes

2024-07-05 02:12 UTC, violetta-klintsova commented on apps/vanilla/src/pages/index.html
> +        <h2 class="font-title books-wrapper__books-year">2022 year</h2>
Skipping heading levels is [not a good practice](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#:~:text=Do%20not%20skip%20heading%20levels%3A%20always%20start%20from%20%3Ch1%3E%2C%20followed%20by%20%3Ch2%3E%20and%20so%20on.). Consider adding `h1`, then `h2` etc. if needed

2024-07-05 02:12 UTC, violetta-klintsova commented on apps/vanilla/src/pages/index.html
> +    <header class="header font-header">📚 Books app</header>
You may want to wrap you heading in typography: 
```suggestion
    <header class="header font-header">
      <h1> 📚 Books app</h1>
    </header>
```
[Header ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)MDN docs :)

2024-07-05 02:17 UTC, violetta-klintsova requested changes
You did a great job! 👍🏼

2024-07-05 03:51 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +      <div>📚 Books app</h1>
Unmatch start and end tag.
```suggestion
      <h1>📚 Books app</h1>
```

2024-07-05 03:51 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +          <div class="font-title">Filter</div>
This should be `h2`, please consider using text related tags such as headings or `p` for text display.

2024-07-05 03:51 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +          <span class="font-header">Books app</span>
When it's a header, consider using heading elements (notice the hierarchy)

2024-07-05 03:51 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +          <form class="form-wrapper__form-control form-control">
The previous naming is acceptable, a form is not `form-control`, form elements is. Review [this definition](https://www.almabetter.com/bytes/tutorials/html/form-controls-in-html) for more information

2024-07-05 04:55 UTC, daoduong-saritasa approved these changes
Great job! :thumbsup:

2024-07-05 04:55 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/index.html
> +          <h2 class="font-title">Filter</h2>
Add missing space for filter title
```suggestion
          <h2 class="font-title">Filters</h2>
```
![image](https://github.com/saritasa-nest/camp-js-2024-dat-ngo/assets/108647643/2f1610b8-daf7-44b7-89d7-532e1bd19e6b)

2024-07-05 06:10 UTC, khoanguyen-saritasa approved these changes
LGTM!

2024-07-05 08:26 UTC, dbitkovski approved these changes

2024-07-05 08:26 UTC, dbitkovski commented on .editorconfig
> +indent_style = space
Right now we use tabs for indent, I guess boilerplate hasn't been updated https://saritasa.slack.com/archives/C079ZH8M78W/p1720166517412459

2024-07-05 10:36 UTC, violetta-klintsova approved these changes

2024-07-08 03:09 UTC, merged