Feature/jc 622 blackjack by dice
saritasa-nest/camp-js-2024-dat-ngo pull request #2
Opened 2024-07-12 09:24 UTC by datngo-saritasa

Create Blackjack By Dice Game to practice Observer Pattern.

2024-07-15 07:27 UTC, artem-sotnichenko-saritasa commented
@datngo-saritasa please fix deploy preview and SonarCloud issue.

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa requested changes

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
> +	--winner-color: rgb(16 227 100/50%);
Let's keep consistent formatting 
```suggestion
	--winner-color: rgb(16 227 100 / 50%);
```

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
In JS and TS we start file names with a small letter. Exception is react components. So please revise your file structure, and updates folder names.

e.g. `../Classes/..` -> `../classes/..`

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +/** ToDo .*/
do ☺️

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +	 */
Please format your multiline jsdoc properly. `/**` and `*/` shouldn't have text for multiline doc.

```suggestion
	/** 
	 * Debugger update the dice result base on the DiceGenerator.
	 * @param playerDiceResult PlayerDuceResult is the dice result of current player.
	 */
```


Also, you can omit subject in the sentence, and be less specific about inner implementation of the function.

```suggestion
	/** 
	 * Update the dice result.
	 * @param playerDiceResult Result of current player.
	 */
```

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +/** Player . */
```suggestion
/** Player. */
```

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +	public readonly winStatus: Publisher<boolean> = new Publisher<boolean>();
We usually use `status` for some multiple statuses. For example, game statuses can be: 'not started', 'in progress', 'completed'.

For boolean variables, we prefer using `is` prefix. For example, `isWon` or `isWinner`.

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +	/** @param turnResult The result of current dice turn which has result and index of player . */
All functions should have description. So functions without params can have singe line jscod, but function with params, should always have multiline jsdoc.
```suggestion
	/** 
	 * Update turn.
	 * @param turnResult The result of current dice turn which has result and index of player.
	 */
```

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +	/** */
Please revisit all jsdoc comments and apply my suggestions above.

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +	}
Really strange that Dice generator have logic about turn.
Applying single responsibility principle(**S**OLID), dice generator should only generate dice number.

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +/** DiceGenerator .*/
Don't just copy variable name. 
```suggestion
/** Dice generator .*/
```

I understand that this doc is pointless, but it's impossible to configure eslint to allow skipping "pointelss" documentation, eslint is not an AI 🫤

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/result-displayer.ts
> +export class WinnerDisplayer implements Subscriber<boolean> {
Please extract it into separate file

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +	}
This logic should probably be moved into `TurnGenerator`

2024-07-15 07:58 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/blackjack/index.css
> +	background-color: #ddd;
Please move colors into variables

2024-07-15 10:17 UTC, datngo-saritasa commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +	}
Sorry I think the name of the property PlayerTurnResult is kinda make you misunderstanding. The PlayerTurnResult is the dice result of the current player in the current turn. The turn-generator only do logic about turn and the PlayerTurnResult is the dice result in current turn.

2024-07-22 04:35 UTC, artem-sotnichenko-saritasa approved these changes

2024-07-24 10:28 UTC, andrey-gazzaev requested changes
Good job. But read this [article](https://deno.com/blog/document-javascript-package) on how to document code.

Good documentation that this is already half the work done

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/react/src/store/genre/slice.ts
> +/** JSDoc. */
Looks like you forgot to write documentation

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/result-displayer.ts
> +}
```suggestion
export type Result {
	readonly diceResult: number[];
	readonly totalScore: number;
}
```

Let's use type for a data structure. Besides, the name of your data structure is not informative, it is also imported, so let's improve the naming

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/turn-generator.ts
> +	 * the result and debugger.
Well done for leaving detailed documentation. But unfortunately, it absolutely does not convey the essence of your method.

In addition, the logic of code execution should be clear from the code, through predictable decisions and good naming of classes, functions, methods, and variables.

Please note that in your description of the logic there are references to classes that simply are not in this class

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/index.ts
> +		const debuggerDisplayer = new ResultDisplayer('Debugger');
The name of the debbuger, which is loosely related to storing game results. Let's choose a different name.

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +		}
Why does a player check if he has won? Shouldn't this be occupied by an entity above the players, such as the game itself?

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/index.ts
> +class App {
```suggestion
class Game {
```
Looks like this class deserves its own file

2024-07-24 10:28 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/index.ts
> +		this.turnGenerator.subscribe(this.diceGenerator);
Please note that you do not unsubscribe from subscriptions anywhere in the game. You could probably do this if you implemented a game stop and started the game again.

2024-07-25 09:24 UTC, datngo-saritasa commented on apps/vanilla/src/pages/blackjack/index.ts
> +		this.turnGenerator.subscribe(this.diceGenerator);
Hi I think this app does not required the stop and start game again base on the requirements.

2024-07-26 10:46 UTC, andrey-gazzaev requested changes

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +export class Debugger extends Inspector implements Subscriber<PlayerTurnResult> {
When I wrote about the name Debugger, I meant that the name of the class is:
1. Intersects with technical terms in programming
2. The name does not reflect the essence of what this class is needed for

Let's improve the name

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +/** Debugger.*/
This documentation is not at all informative. Let's add what this class is for.

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +	public update(playerDiceResult: PlayerTurnResult): void {
```suggestion
	/** @inheritdoc */
	public update(playerDiceResult: PlayerTurnResult): void {
```

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +	/** Win index of player.*/
```suggestion
	/** Winning player index.*/
```

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +/** Player. */
Please improve the documentation

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/dice-generator.ts
> +	}
```suggestion
	/** Rolls the dice. */
	public roll(): number {
		return getRandomIntegerNumber(SIDE_COUNT);
	}
```

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/inspector.ts
> +/** Inspector is the class illustrate the member that subscribe to the game. */
```suggestion
/** The class illustrates the member that subscribe to the game. */
```

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/inspector.ts
> +	public readonly result: Publisher<Result> = new Publisher<Result>();
The documentation describes the field as if it were a function

2024-07-26 10:46 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/result-displayer.ts
> +}
```suggestion
/** Result. */
export type Result = {
	readonly diceResult: number[],
	readonly totalScore: number
}
```

Use  types

2024-08-01 02:49 UTC, andrey-gazzaev approved these changes
Well done!

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +		this.result.notify(newResult);
```suggestion
		this.result.notify({
			diceResult: diceResults,
			totalScore: this.getTotalScore,
		});
```

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Debugger.ts
> +/** ResultHistory update the dice result base on the DiceGenerator.*/
Reading this documentation I imagine that ResultHistory is a function that updates something:

`ResultHistory()`

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +	public update(turnResult: PlayerTurnResult): void {
```suggestion
  /** @inheritdoc */
	public update(turnResult: PlayerTurnResult): void {
```
Please check all places in the code when they write to you to fix or improve something.

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/Player.ts
> +			this.result.notify(newResult);
same

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/result-displayer.ts
> +	private createElement(htmlString: string): HTMLElement | null {
```suggestion
	/**
	 * Сreates new HTML elements .
	 * @param htmlString String of HTML elements.
	 */
	private createElement(htmlString: string): HTMLElement | null {
```

2024-08-01 02:49 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/blackjack/Classes/winner-displayer.ts
> +		}
```suggestion
    const buttonElement = winnerIndex != null ? document.getElementById('button-roll')  : document.getElementById('button-reset');
		if (winnerIndex != null) {
			this.containerElement = document.getElementById(`Player-${(winnerIndex + 1)}`);
			this.containerElement?.classList.add('win');
		}
		
		if (isHTMLButtonElement(buttonElement)) {
				buttonElement.disabled = true;
			}
```

Try to come up with solutions in such a way as to avoid unnecessary nesting

2024-08-05 10:04 UTC, merged