Feature: initialize anime app and table view angular JC-638
saritasa-nest/camp-js-2024-dat-ngo pull request #3
Opened 2024-07-23 08:54 UTC by datngo-saritasa

Initialize anime app and table view angular JC-638

2024-08-07 10:01 UTC, daoduong-saritasa requested changes

2024-08-07 10:01 UTC, daoduong-saritasa commented on libs/core/utils/utils.ts
> +export function changeIfValueEmpty(value: string): string {
Is this function use anywhere?

2024-08-09 02:48 UTC, datngo-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	private readonly animeService = inject(AnimeService);
For this one because I've to use animePage$ on the html file so protected is a must.

2024-08-09 07:15 UTC, daoduong-saritasa approved these changes

2024-08-09 07:16 UTC, daoduong-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.ts
> +	private readonly animeService = inject(AnimeService);
What I mean is this
```suggestion
	private readonly animeService = inject(AnimeService);

	protected readonly animePage$: Observable<Pagination<Anime>>;
```

2024-08-19 04:35 UTC, shalomich approved these changes

2024-08-19 04:35 UTC, shalomich commented on libs/core/models/amime-type.ts
> +export enum AnimeType {
Typo in the file name

2024-08-19 04:35 UTC, shalomich commented on libs/core/types/BroadcastedTime.type.ts
> +export type BroadCastedTime = {
Let's move this type to the models folder

2024-08-19 04:35 UTC, shalomich commented on libs/core/models/pagination.ts
> +export class Pagination<T> extends Immerable {
Now we prefer to use `type` instead of `class`. But you've already done this with the help of classes, you don't need to redo it, it's just for information

2024-08-19 04:35 UTC, shalomich commented on libs/core/models/pagination.ts
> +export class Pagination<T> extends Immerable {
Why do we need extends `Immerable`?

2024-08-19 04:35 UTC, shalomich commented on libs/core/models/anime.model.ts
> +	public readonly coverImage: string;
Is it URL?

```suggestion
	public readonly coverImageUrl: string;
```

2024-08-19 04:35 UTC, shalomich commented on libs/core/models/anime.model.ts
> +	public readonly titleJpn: string;
```suggestion
	public readonly englishTitle: string;

	/** Title in Japanese. */
	public readonly japaneseTitle: string;
```

2024-08-19 04:35 UTC, shalomich commented on libs/core/mappers/anime.mapper.ts
> +const MAP_ANIME_STATUS_FROM_DTO: Record<AnimeStatusDto, AnimeStatus> = {
It is good solution but let's move maps to separate classes: `AnimeStatusMapper` and `AnimeTypeMapper`

2024-08-19 04:35 UTC, shalomich commented on libs/core/dtos/amime-type.dto.ts
> +export enum AnimeTypeDto {
Typo in file name

2024-08-19 04:35 UTC, shalomich commented on libs/core/dtos/anime.dto.ts
> +	readonly aired: {
Let's create `BroadcastedTimeDto`

2024-08-19 08:44 UTC, danilkukryakov requested changes

2024-08-19 08:44 UTC, danilkukryakov commented on libs/core/types/mapper.ts
> +export type TMapperFromDto<TDto, TDomain> = {
Please, remove 'T' prefix everywhere (except generic types).

2024-08-19 08:44 UTC, danilkukryakov commented on libs/core/dtos/anime.dto.ts
> +	readonly modified: string;
Provide this comment for string dates everywhere.

2024-08-19 08:44 UTC, danilkukryakov commented on libs/theme/src/variables.css
> +	--spacing-xxl: 40px;
It's better to use base spacing + 'calc' function. It may look like this:
```suggestion
	--spacing-sm: 8px;
	--spacing-md: calc(var(--spacing-sm) * 2);
	--spacing-default: calc(var(--spacing-sm) * 2.5);
	--spacing-lg: calc(var(--spacing-sm) * 3);
	--spacing-xl: calc(var(--spacing-sm) * 4);
	--spacing-xxl: calc(var(--spacing-sm) * 5);
```

2024-08-19 08:44 UTC, danilkukryakov commented on libs/theme/src/variables.css
> +	--form-height: 48px;
If I'm not mistaken these variables are duplication of CSS variables from Vanilla project. Are you planning to use them in your Angular project?
It's better to remove unused variables to make code cleaner.

2024-08-20 05:10 UTC, datngo-saritasa commented on libs/core/models/pagination.ts
> +export class Pagination<T> extends Immerable {
I think because we will reuse it in react and immerable is for the react state mutation.

2024-08-20 06:35 UTC, datngo-saritasa commented on apps/angular/src/shared/app-url.ts
> +		list: this.toApi('anime/anime/'),
For this case, I want to join the` 'anime/anime/'` with the base url string to make an API url

2024-08-20 06:37 UTC, datngo-saritasa commented on libs/core/types/mapper.ts
> +export type TMapper<TDto, TDomain> = TMapperFromDto<TDto, TDomain> & TMapperToDto<TDto, TDomain>;
Yes I prepare this for the next tasks and in the next task you will see I use this interface alots.

2024-08-20 06:41 UTC, danilkukryakov commented on apps/angular/src/shared/app-url.ts
> +		list: this.toApi('anime/anime/'),
Inside 'toApi' function you have code like this:
> const relativePath = args.join('/');

So 'this.toApi('anime', 'anime')' will be converted to base url string + 'anime/anime/'.
If it doesn't work like this then probably 'toApi' function should be adjusted.

2024-08-20 07:37 UTC, datngo-saritasa commented on libs/core/mappers/anime.mapper.ts
> +			modified: anime.modifiedDate.toISOString(),
So does it means the data we POST with the API would be string and it the BE side jobs to parse it to Date type ?

2024-08-20 07:43 UTC, danilkukryakov commented on libs/core/mappers/anime.mapper.ts
> +			modified: anime.modifiedDate.toISOString(),
Usually we don't send properties like 'modified' or 'created' in POST request body payload. Backend doesn't expect these values to come from the frontend, so in most cases it just ignores them.

2024-08-20 08:20 UTC, danilkukryakov approved these changes

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/dtos/broadcasted-time.dto.ts
> +export type BroadCastedTimeDto = {
Let's use more generic name for this DTO. We have several cases where such DTO might be used.
My suggestion will be to call it `DateRangeDto` (you may use alternative name if you wish).

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/dtos/anime.dto.ts
> +	};
Let's use ~~BroadCastedTimeDto~~ `DateRangeDto` here to reduce code duplication:
```suggestion
	readonly aired: DateRangeDto;
```

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/mappers/anime-type.mapper.ts
> +export class AnimeTypeMapper {
Let's convert this mapper to namespace for consistency with other mappers.

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/mappers/anime-status.mapper.ts
> +export class AnimeStatusMapper {
Let's convert this mapper to namespace for consistency with other mappers.

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/mappers/broadcasted-time.mapper.ts
> +export namespace broadCastedTimeMapper {
Namespace should follow PascalCase convention:
```suggestion
export namespace BroadCastedTimeMapper {
```

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/broadcasted-time.model.ts
> +export class BroadCastedTime extends Immerable {
Let's rename this model to `DateRange`. We can use it for different scenarios, not only for broadcasted time.
Besides, don't forget to align mapper and DTO name to be consistent.

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/broadcasted-time.model.ts
> +	public endDate: Date | null;
Properties should be readonly (see our [wiki](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#interfaces)):
```suggestion
	public readonly startDate: Date | null;

	/** An anime can have a end date if it ends already or null if it not end yet. */
	public readonly endDate: Date | null;
```

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/broadcasted-time.model.ts
> +export class BroadCastedTime extends Immerable {
Please, fix comment here.

2024-08-20 08:20 UTC, danilkukryakov commented on libs/theme/src/variables.css
> +	--on-primary-color: rgb(255 255 255);
Please, don't mark comment 'Resolved' without any actions.
If you don't agree with the comment or reviewer's suggestion is incorrect you should leave a comment about it and then 'Resolve'.
When you don't change code don't forget to leave a comment, so it doesn't seem like you just ignored the comment 😅

2024-08-20 08:20 UTC, danilkukryakov commented on package.json
> +    "@angular/material": "^18.1.0",
This dependency is duplicated for some reason. '@angular/material' should be declared once in the 'dependencies' section (not in 'devDependencies').

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/pagination.ts
> +export type PaginationConstructorData<T> = OmitImmerable<Pagination<T>>;
We don't use this type outside this file. So we can omit 'export':
```suggestion
type PaginationConstructorData<T> = OmitImmerable<Pagination<T>>;
```

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/anime.model.ts
> +type PaginationConstructorData = OmitImmerable<Anime>;
Fix name of the type here.

2024-08-20 08:20 UTC, danilkukryakov commented on libs/core/models/anime.model.ts
> +	public readonly genres: readonly string[];
Let's use more descriptive names for these properties.
```suggestion
	/** Studio's id as array of string. */
	public readonly studioIds: readonly string[];

	/** Genres' id as array of string. */
	public readonly genreIds: readonly string[];
```

2024-08-21 02:49 UTC, datngo-saritasa commented on apps/angular/src/app/features/home/anime-table/anime-table.component.html
> +	<section class="mat-elevation-z8 anime__table-container" >
Completely agree, I have remove the `section` element and move the css to the :host.

2024-08-21 03:46 UTC, datngo-saritasa commented on libs/core/dtos/broadcasted-time.dto.ts
> +export type BroadCastedTimeDto = {
Totally agree, I have changed it.

2024-08-21 03:50 UTC, datngo-saritasa commented on libs/theme/src/variables.css
> +	--on-primary-color: rgb(255 255 255);
I think this was on the design for the vanilla application. I will try to make other name for this.
![image](https://github.com/user-attachments/assets/f31a6fbf-5b5c-40b7-8ec8-f317028e209a)

2024-08-21 03:52 UTC, datngo-saritasa commented on libs/core/mappers/anime.mapper.ts
> +			modified: anime.modifiedDate.toISOString(),
I will remove `created` and `modified` from dto, model and mapper.

2024-08-21 03:53 UTC, datngo-saritasa commented on package.json
> +    "@angular/material": "^18.1.0",
I will remove this dependencies.)

2024-08-24 09:26 UTC, merged