Feature/jc 656 anime list management
saritasa-nest/camp-js-2024-dat-ngo pull request #4
Opened 2024-08-07 04:40 UTC by datngo-saritasa

Anime list management JC-656. I make a Anime table management included Paginator, Search Input and Selector.

2024-08-07 08:22 UTC, viktor-sakhno-saritasa approved these changes

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/home/anime-catalog/anime-catalog.component.html
> +	></camp-search-filter-form>
You can use self-closing tags.
```suggestion
	<camp-search-filter-form
		(typeChange)="onSelectionChange($event)"
		(searchChange)="onSearchChange($event)"
		[search]="data.filterParams?.search ?? ''"
		[selectedType]="data.filterParams?.type ?? null"
	/>
```

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/home/anime-catalog/anime-catalog.component.spec.ts
Let's remove redundant specs.

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/home/anime-catalog/components/anime-table/anime-table.component.ts
> +	protected dataSource = new MatTableDataSource<Anime>();
Why do we need `MatTableDataSource`? Why we can't use pagination items value directly in the template?

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/home/anime-catalog/components/paginator/paginator.component.ts
> +	// TODO (Dat Ngo): Put Input and Output correctly DONE.
Is it an expired comment? If yes, let's remove it.

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/home/anime-catalog/components/search-filter-form/search-filter-form.component.css
> +	/* TODO (Dat Ngo): Use var. */
Remove.

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +	// TODO (Dat Ngo): Move this to anime service. DONE
As I understand, you mark completed to-dos with `DONE` word. So, it would be better just to remove it.

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/shared/components/table-cell-content/table-cell-content.component.ts
> +	@Input() private width = '100%';
```suggestion
	@Input() 
	private width = '100%';
```

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on apps/angular/src/shared/components/table-cell-content/table-cell-content.component.ts
> +	@Input() private height = 24;
```suggestion
	@Input() 
	private height = 24;
```

2024-08-07 08:22 UTC, viktor-sakhno-saritasa commented on libs/core/models/anime.model.ts
Why do you use `model` keyword for the model? I think `anime.ts` would be enough.

2024-08-14 07:27 UTC, DaniilMaslovSaritasa approved these changes

2024-08-14 07:27 UTC, DaniilMaslovSaritasa commented on apps/angular/src/shared/components/table-cell-content/table-cell-content.component.ts
> +	private height = 24;
Unused variables

2024-08-15 10:47 UTC, datngo-saritasa commented on libs/core/dtos/based-filter-params.dto.ts
> +		readonly limit?: number;
I think this should be optional because when we send this to backend the params are optional.

2024-08-15 10:55 UTC, datngo-saritasa commented on apps/angular/src/app/features/home/anime-catalog/anime-catalog.component.ts
> +	private readonly sortMapper = inject(SortMapper);
This is not the mapper for the service to send data to backend. This is the mapper to map the data in UI to the URL on the browser. Therefore, I think it's okay to put it in the UI layer.

2024-08-17 11:17 UTC, SofyaKirillova approved these changes

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime/anime-catalog/anime-catalog.component.ts
> +		const DEBOUNCE_TIME = 1000;
Move it higher, above the class

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime/anime-catalog/anime-catalog.component.ts
> +			switchMap((queryParams) =>
```suggestion
			switchMap(queryParams =>
```

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/shared/components/anime-status/anime-status.component.ts
>  /** Movie status. */
```suggestion
/** Anime status component. */
```

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/app/features/anime/anime-catalog/components/anime-not-found/anime-not-found.component.spec.ts
We don't have any testing. This file can be deleted

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/shared/components/anime-status/anime-status.component.spec.ts
We don't have any testing. This file can be deleted

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/shared/components/movie-type/movie-type.component.ts
Rename the file and folder. Replace movie with anime

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/theme/elements/index.css
> +@import url("./movie-badge.css");
```suggestion
@import url("./anime-status.css");
@import url("./anime-type.css");
@import url("./anime-badge.css");
```

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/shared/components/movie-type/movie-type.component.ts
> +	selector: 'camp-movie-type',
```suggestion
	selector: 'camp-anime-type',
```
Check the entire file

2024-08-17 11:17 UTC, SofyaKirillova commented on apps/angular/src/shared/components/movie-type/movie-type.component.ts
> +export class MovieTypeComponent {
It seems that this component is'nt being used

2024-08-27 05:22 UTC, danilkukryakov requested changes

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-catalog/components/search-filter-form/search-filter-form.component.html
> +<section class="main">
Do we really need this 'section' wrapper? Can we apply related CSS styles to :host selector instead?

It's better to reduce code nesting to improve code readability. That's the reason we try to avoid unnecessary wrappers in the template.

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-catalog/components/search-filter-form/search-filter-form.component.css
> +}
If you have Angular Material in your project I recommend you to take a look at [Button](https://material.angular.io/components/button/overview) component.
It has a nice look and lots of customization options out of the box.

For example:
```html
<button mat-flat-button type="button">Click me!</button>
```

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-catalog/components/anime-table/anime-table.component.ts
> +	}
'templateArray' seems like a small hack to me. Is it possible to use empty array instead?
```html
<!-- anime-table.component.html -->
<table
	mat-table
	[dataSource]="isLoading ? [] : dataSource"
>
```

Anyway, if you want to use your own solution, then getter is an overhead here. We can simplify the solution:
```suggestion
	protected readonly templateArray: readonly unknown[] = Array(DEFAULT_PAGINATION.pageSize).fill(null);
```

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/app/features/anime/anime-catalog/components/anime-table/anime-table.component.ts
> +	public onSortChange(event: Sort): void {
Prefer to use `protected` access modifier for methods and properties which are used in the component's template:
```suggestion
	protected onSortChange(event: Sort): void {
```

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/core/services/anime.service.ts
> +	private animeQueryMapper = inject(AnimeFiltersParamsMapper);
Don't forget about `readonly` access modifier:
```suggestion
	private readonly httpParamsService = inject(HttpParamsService);

	private readonly appUrlsConfig = inject(AppUrlsConfig);

	private readonly animeQueryMapper = inject(AnimeFiltersParamsMapper);
```

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/shared/components/anime-status/anime-status.component.ts
> +	}
'_classes' property seems redundant to me. You can just make it 'protected' to avoid linter errors:
```suggestion
      	@HostBinding('class')
	protected get classes(): string {
		return `anime-badge ${this.color}`;
	}
```

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/shared/components/anime-status/anime-status.component.ts
> +	}
As far as I can see you have similar code in other component. Please, fix it as well.

2024-08-27 05:22 UTC, danilkukryakov commented on apps/angular/src/shared/components/anime-type/anime-type.component.ts
> +	public animeType!: AnimeType;
It's not recommended to use `!` operator. Please, rework this. You can use `AnimeStatusComponent` for reference.

2024-08-27 05:22 UTC, danilkukryakov commented on libs/core/const/pagination.ts
> +	pageSize: number;
```suggestion
	/** Page number. */
	readonly pageNumber: number;

	/** Page size. */
	readonly pageSize: number;
```

2024-08-27 05:22 UTC, danilkukryakov commented on libs/theme/src/variables.css
> +	--anime-japan-title-row-color: rgb(53 141 235);
I have some doubts about such large color palette. Usually we have 3-4 base color and try to use them and their modifications (e.g. light/dark version) everywhere.
Color palette with 20+ color are hard to maintain and it might bring inconsistency in our app.

Anyway, I just saying my concern. You can leave this without changes if you wish. As far as I can remember we don't have any strict requirements about the UI.

2024-08-27 09:02 UTC, datngo-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/components/search-filter-form/search-filter-form.component.html
> +		<mat-select [(value)]="selectedType" (selectionChange)="onSelectionChange($event)">
I have check all the place and fixed.

2024-08-27 09:50 UTC, datngo-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/components/anime-table/anime-table.component.ts
> +	}
Hi Danil, my solution require an array of object to perform the skeleton loading. The empty array is also consider but I have 2 variables isLoading and the dataSource for the displayed table. If isLoading = true we will use the empty array of object, isLoading = false && dataSource.length != 0 then we display out the data. If the array is empty and isLoading = false then we display not found pages.
`	/** Generate number array for the template table data source. */
	protected readonly templateArray: readonly unknown[] = Array(DEFAULT_PAGINATION.pageSize).fill({});`
I have use your code as inspiration for this code to create a new array of  empty object.

2024-08-27 13:56 UTC, datngo-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/components/search-filter-form/search-filter-form.component.html
> +			<input matInput [(ngModel)]="search" placeholder="Anime Name" (keydown)="onKeyDown($event)" (onchange)="onSearch()" />
I have migrate to formControl from Angular Reactive Forms instead of Angular template form

2024-08-27 14:05 UTC, datngo-saritasa commented on libs/theme/src/variables.css
> +	--anime-japan-title-row-color: rgb(53 141 235);
I have ask mentors at Vietnam Office too, and it seems in real project we only have 3-4 colors with other modifications as your statement. So in the future I will follow that convention, but in this internship project I want to have some color for specific tag then I will keep these color variables but I will move them into the `anime-status.component` and `anime-type.component`. Those are 2 only components that use those color and it's better not to store them in the global css like this.) Thanks for your suggestion again.

2024-08-28 02:37 UTC, datngo-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/components/search-filter-form/search-filter-form.component.css
> +}
I have add mat-flat-button to the button.

2024-08-29 08:41 UTC, danilkukryakov approved these changes

2024-08-29 09:14 UTC, merged