Feature/jc 675 authorization feature angular
saritasa-nest/camp-js-2024-dat-ngo pull request #5
Opened 2024-08-21 08:57 UTC by datngo-saritasa

Create authorization function for anime app.

2024-08-22 06:04 UTC, shalomich commented
Uploading bug.mp4…

2024-08-22 06:05 UTC, shalomich commented
https://github.com/user-attachments/assets/c2971035-9f1b-44a6-a759-800319c1602c

2024-08-22 08:04 UTC, shalomich requested changes

2024-08-22 08:04 UTC, shalomich commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +			password: ['', [Validators.required, Validators.minLength(8)]],
Please have constant for minLength and to reuse it in `signin.component`

2024-08-22 08:04 UTC, shalomich commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +			reTypePassword: ['', [Validators.required, Validators.minLength(8)]],
What if `retypePassword` doesn't match `password`?

2024-08-22 08:06 UTC, shalomich commented
@datngo-saritasa I cannot view files unrelated to authorization, because I suspect they may not be relevant from other PR reviews. Therefore, before you ask me again for this PR, I ask you to merge other PRs into the dev and update your branch regarding it

2024-08-22 08:08 UTC, shalomich commented
@datngo-saritasa Please fix linting and SonarCloud error

2024-08-25 05:51 UTC, datngo-saritasa commented on apps/angular/src/app/auth/auth.component.html
> +			<section class="main__copyright">
I have read through the docs so `<section>`  is refers to a standalone group of content that do not have any sematic tag fit to its but have to have a header. So in this case if we did not have any specific tag and cannot use `<section>`, we can use `div` like a division of content.

2024-08-25 05:56 UTC, datngo-saritasa commented on apps/angular/src/app/auth/components/password-input/password-input.component.css
> +	color: var(--anime-japan-title-row-color);
For this I just reuse the color for those 2 field I will make another name for the color variable.

2024-08-25 06:02 UTC, datngo-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.css
> +	color: var(--anime-button);
Same problems I reuse the color but not have a general name so I will redo the color name.

2024-08-25 06:14 UTC, datngo-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.html
> +		<a href="#" class="form__forgot-password">Forgot password?</a>
I will remove the `href` link but leave the `<a>` element for later use.

2024-08-25 06:37 UTC, datngo-saritasa commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +			reTypePassword: ['', [Validators.required, Validators.minLength(8)]],
Sorry I have develop a mustMatch Fn in `apps\angular\src\core\utils\custom-validator.ts` but havent use it. Thank for remind me.

2024-08-26 07:20 UTC, daoduong-saritasa requested changes
This branch should be merge into `feature/JC-656-anime-list-management` not `develop`. Seem like you checkout from `JC-656` and it's not merge to develop yet, so this branch will contain both `JC-656` and `JC-675` commits when merge to develop.

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.html
> +	<button type="submit" class="form__btn-signin" [disabled]="signInForm.invalid && (isLoading$ | async)">
This should be `||` , `isLoading$` can't be triggered if form is invalid

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.ts
> +/** Signin. */
```suggestion
/** Signin component. */
```

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.ts
> +	private formBuilder = inject(NonNullableFormBuilder);
```suggestion
	private readonly formBuilder = inject(NonNullableFormBuilder);
```

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.ts
> +		],
```suggestion
		email: this.formBuilder.control('', [
				Validators.required,
				Validators.email,
				Validators.minLength(EMAIL_MIN_LENGTH),
				Validators.maxLength(EMAIL_MAX_LENGTH),
			]),
```

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.ts
> +	 * @param controlName Name of the control.
```suggestion
	/** 
	 * Display error.
	 * @param controlName Name of the control.
```

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.ts
> +	 *	Get Error message.
Wrong indentation

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +	private formBuilder = inject(NonNullableFormBuilder);
```suggestion
	private readonly formBuilder = inject(NonNullableFormBuilder);
```

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +		email: [
Please update form control with `this.formBuilder.control`

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/auth/components/signup/signup.component.ts
> +		if (this.signUpForm.valid) {
Please use early return with `this.signUpForm.invalid`

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/anime-catalog.component.ts
> +			debounceTime(1000),
Avoid to use magic number, declare a variable instead

2024-08-26 07:20 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime/anime-catalog/anime-catalog.component.ts
> +	/** Subscribe the filter params and pass them to the filter form and paginator. */
Use `/** @inheritdoc */` for life-cycle functions, the name of the side effect should explain what it does, not life-cycle docs

2024-08-27 14:35 UTC, datngo-saritasa commented on apps/angular/src/app/auth/components/signin/signin.component.html
> +	<div class="form__input-group">
I have add the form class for the form.

2024-09-03 04:05 UTC, closed without merging